version: "3.8"

services:
  app:
    build: .
    container_name: my-express-app
    restart: unless-stopped
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    container_name: my-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - webnet


networks:
  webnet:
    driver: bridge
